title: Sample Docs
description: This is a sample documentation site. 
theme: just-the-docs

url: https://eo33.github.io/just-the-docs-test

aux_links: 
  Template Repository: https://eo33.github.io/just-the-docs-test
  Homepage: https://eo33.github.io/

search_enabled: true

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

## Callout themes
callouts:
  warning:
    title: warning
    color: yellow
  note:
    title: note
    color: purple
  new:
    title: new
    color: green
  danger:
    title: danger
    color: red
  important:
    title: important
    color: blue

## Mermaid diagrams
mermaid:
  version: "11.7.0"

## Plugins
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Site metadata (used by jekyll-seo-tag)
title: Sample docs
description: A short summary of what your site or documentation is about.
lang: en
author:
  name: eo33
  email: edorlando33@gmail.com
