title: Sample Docs
description: This is a sample documentation site. 
theme: just-the-docs

url: https://eo33.github.io/just-the-docs-test

aux_links: 
  Template Repository: https://eo33.github.io/just-the-docs-test

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607